# start from base
FROM node:boron

# set env vars
ENV NODE_ENV testing

# install all dependencies in working dir
ADD . /usr/src/app
WORKDIR /usr/src/app
RUN npm install --quiet
COPY node_modules temp_modules/
