# start from base
FROM node:boron

# set env vars
ENV NODE_ENV production

# copy our app and dependency code
ADD . /usr/src/app
ADD ./tmp/node_modules /usr/src/app
WORKDIR /usr/src/app

# build dist files in given env-mode
RUN npm run build

# remove non-prod deps
RUN rm -rf node_modules
RUN npm install --quiet
